const palette = {
  bg: "#0e0e0e",
  surface: "#111111",
  surfaceAlt: "#1a1a1a",
  surfaceHigh: "#1e1e1e",
  border: "#1e1e1e",
  borderStrong: "#2a2a2a",
  text: "#f0f0f0",
  textMuted: "#666666",
  textDim: "#444444",
  accent: "#b4ff6e",
  accentSoft: "rgba(180,255,110,0.15)",
  accentDim: "rgba(180,255,110,0.07)",
  accentRing: "rgba(180,255,110,0.45)",
  danger: "#ff4d4d",
  recording: "#ff4d4d",
};

const colors = {
  light: {
    text: palette.text,
    tint: palette.accent,
    background: palette.bg,
    foreground: palette.text,
    card: palette.surface,
    cardForeground: palette.text,
    cardAlt: palette.surfaceAlt,
    cardHigh: palette.surfaceHigh,
    primary: palette.accent,
    primaryForeground: "#0a0a0a",
    secondary: palette.surfaceAlt,
    secondaryForeground: palette.text,
    muted: palette.surfaceAlt,
    mutedForeground: palette.textMuted,
    accent: palette.accent,
    accentForeground: "#0a0a0a",
    accentSoft: palette.accentSoft,
    accentDim: palette.accentDim,
    accentRing: palette.accentRing,
    destructive: palette.danger,
    destructiveForeground: "#ffffff",
    border: palette.border,
    borderStrong: palette.borderStrong,
    input: palette.border,
    textDim: palette.textDim,
    recording: palette.recording,
  },
  dark: {
    text: palette.text,
    tint: palette.accent,
    background: palette.bg,
    foreground: palette.text,
    card: palette.surface,
    cardForeground: palette.text,
    cardAlt: palette.surfaceAlt,
    cardHigh: palette.surfaceHigh,
    primary: palette.accent,
    primaryForeground: "#0a0a0a",
    secondary: palette.surfaceAlt,
    secondaryForeground: palette.text,
    muted: palette.surfaceAlt,
    mutedForeground: palette.textMuted,
    accent: palette.accent,
    accentForeground: "#0a0a0a",
    accentSoft: palette.accentSoft,
    accentDim: palette.accentDim,
    accentRing: palette.accentRing,
    destructive: palette.danger,
    destructiveForeground: "#ffffff",
    border: palette.border,
    borderStrong: palette.borderStrong,
    input: palette.border,
    textDim: palette.textDim,
    recording: palette.recording,
  },
  radius: 14,
};

export default colors;
