const palette = {
  bg: "#0a0a0b",
  surface: "#131317",
  surfaceAlt: "#1a1a20",
  surfaceHigh: "#22222a",
  border: "#26262d",
  borderStrong: "#34343d",
  text: "#f3f3f5",
  textMuted: "#9a9aa3",
  textDim: "#5a5a64",
  accent: "#e8a663",
  accentSoft: "rgba(232,166,99,0.18)",
  accentDim: "rgba(232,166,99,0.08)",
  accentRing: "rgba(232,166,99,0.5)",
  danger: "#e36f6f",
  recording: "#e35b5b",
};

const colors = {
  light: {
    text: palette.text,
    tint: palette.accent,
    background: palette.bg,
    foreground: palette.text,
    card: palette.surface,
    cardForeground: palette.text,
    cardAlt: palette.surfaceAlt,
    cardHigh: palette.surfaceHigh,
    primary: palette.accent,
    primaryForeground: "#0a0a0b",
    secondary: palette.surfaceAlt,
    secondaryForeground: palette.text,
    muted: palette.surfaceAlt,
    mutedForeground: palette.textMuted,
    accent: palette.accent,
    accentForeground: "#0a0a0b",
    accentSoft: palette.accentSoft,
    accentDim: palette.accentDim,
    accentRing: palette.accentRing,
    destructive: palette.danger,
    destructiveForeground: "#ffffff",
    border: palette.border,
    borderStrong: palette.borderStrong,
    input: palette.border,
    textDim: palette.textDim,
    recording: palette.recording,
  },
  dark: {
    text: palette.text,
    tint: palette.accent,
    background: palette.bg,
    foreground: palette.text,
    card: palette.surface,
    cardForeground: palette.text,
    cardAlt: palette.surfaceAlt,
    cardHigh: palette.surfaceHigh,
    primary: palette.accent,
    primaryForeground: "#0a0a0b",
    secondary: palette.surfaceAlt,
    secondaryForeground: palette.text,
    muted: palette.surfaceAlt,
    mutedForeground: palette.textMuted,
    accent: palette.accent,
    accentForeground: "#0a0a0b",
    accentSoft: palette.accentSoft,
    accentDim: palette.accentDim,
    accentRing: palette.accentRing,
    destructive: palette.danger,
    destructiveForeground: "#ffffff",
    border: palette.border,
    borderStrong: palette.borderStrong,
    input: palette.border,
    textDim: palette.textDim,
    recording: palette.recording,
  },
  radius: 14,
};

export default colors;
