const palette = {
  bg: "#0a0a0a",
  surface: "#111111",
  surfaceAlt: "#1a1a1a",
  surfaceHigh: "#141414",
  border: "#1e1e1e",
  borderStrong: "#2e2e2e",
  text: "#fafafa",
  textMuted: "#666666",
  textSecondary: "#999999",
  textDim: "#444444",
  accent: "#c4f441",
  accentSoft: "rgba(196,244,65,0.15)",
  accentDim: "rgba(196,244,65,0.08)",
  accentRing: "rgba(196,244,65,0.5)",
  danger: "#ff4d4d",
  recording: "#ff4d4d",
};

const token = {
  text: palette.text,
  tint: palette.accent,
  background: palette.bg,
  foreground: palette.text,
  surface: palette.surface,
  card: palette.surface,
  cardForeground: palette.text,
  cardAlt: palette.surfaceAlt,
  cardHigh: palette.surfaceHigh,
  primary: palette.accent,
  primaryForeground: "#0a0a0a",
  secondary: palette.surfaceAlt,
  secondaryForeground: palette.text,
  muted: palette.surfaceAlt,
  mutedForeground: palette.textMuted,
  accent: palette.accent,
  accentForeground: "#0a0a0a",
  accentSoft: palette.accentSoft,
  accentDim: palette.accentDim,
  accentRing: palette.accentRing,
  destructive: palette.danger,
  destructiveForeground: "#ffffff",
  border: palette.border,
  borderStrong: palette.borderStrong,
  input: palette.border,
  textDim: palette.textDim,
  textMuted: palette.textMuted,
  textSecondary: palette.textSecondary,
  recording: palette.recording,
};

const colors = {
  light: token,
  dark: token,
  radius: 12,
};

export default colors;
